language: python

python:
    - "3.4"
    
cache: pip
    
services:
    - mysql

env:
    - DJANGO=1.11.1 SCOPE_DB_HOST=127.0.0.1 SCOPE_DB_USER=root SCOPE_DB_PASS="" SCOPE_DB_PORT=3306 SCOPE_SECRET_KEY=key
    
before_install:
    - export DJANGO_SETTINGS_MODULE=settings
    - export PYTHONPATH=$HOME/builds/tckerr/scope
    - export PIP_USE_MIRRORS=true
  
install:
    - pip install -r scope.api/app/requirements.txt
  
script:
    - cd scope.api/app
    - python manage.py test
    
notifications:
    email:
        recipients:
            - tckerr@gmail.com
        on_success: never # default: change
        on_failure: always # default: always