&"$($PSScriptRoot)/scripts/start_machine.ps1"
&"$($PSScriptRoot)/scripts/build_docker_image.ps1"
&"$($PSScriptRoot)/scripts/run_latest.ps1"
&"$($PSScriptRoot)/scripts/push_latest_image.ps1"
&"$($PSScriptRoot)/scripts/deploy_to_aws.ps1"