# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-22 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Actor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(through='project.Membership', to='project.Actor'),
        ),
    ]
