# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-22 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180421_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='membership',
            name='datetime_joined',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='datetime_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
