# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-22 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180421_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
