# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-22 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20180422_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
