# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-22 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_jobstatus_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstatus',
            name='workstream',
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='project.Organization'),
            preserve_default=False,
        ),
    ]
